// Code generated by protoc-gen-go. DO NOT EDIT.
// source: resources/proto/RegionWasCreated.proto

package HelloFresh_Message_DeliveryRegions

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RegionWasCreated struct {
	RegionId             string   `protobuf:"bytes,1,opt,name=regionId,proto3" json:"regionId,omitempty"`
	Country              string   `protobuf:"bytes,2,opt,name=country,proto3" json:"country,omitempty"`
	Handle               string   `protobuf:"bytes,3,opt,name=handle,proto3" json:"handle,omitempty"`
	Name                 string   `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	ListId               string   `protobuf:"bytes,5,opt,name=listId,proto3" json:"listId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegionWasCreated) Reset()         { *m = RegionWasCreated{} }
func (m *RegionWasCreated) String() string { return proto.CompactTextString(m) }
func (*RegionWasCreated) ProtoMessage()    {}
func (*RegionWasCreated) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce4acc90720b99e4, []int{0}
}

func (m *RegionWasCreated) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegionWasCreated.Unmarshal(m, b)
}
func (m *RegionWasCreated) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegionWasCreated.Marshal(b, m, deterministic)
}
func (m *RegionWasCreated) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegionWasCreated.Merge(m, src)
}
func (m *RegionWasCreated) XXX_Size() int {
	return xxx_messageInfo_RegionWasCreated.Size(m)
}
func (m *RegionWasCreated) XXX_DiscardUnknown() {
	xxx_messageInfo_RegionWasCreated.DiscardUnknown(m)
}

var xxx_messageInfo_RegionWasCreated proto.InternalMessageInfo

func (m *RegionWasCreated) GetRegionId() string {
	if m != nil {
		return m.RegionId
	}
	return ""
}

func (m *RegionWasCreated) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

func (m *RegionWasCreated) GetHandle() string {
	if m != nil {
		return m.Handle
	}
	return ""
}

func (m *RegionWasCreated) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RegionWasCreated) GetListId() string {
	if m != nil {
		return m.ListId
	}
	return ""
}

func init() {
	proto.RegisterType((*RegionWasCreated)(nil), "HelloFresh.Message.DeliveryRegions.RegionWasCreated")
}

func init() {
	proto.RegisterFile("resources/proto/RegionWasCreated.proto", fileDescriptor_ce4acc90720b99e4)
}

var fileDescriptor_ce4acc90720b99e4 = []byte{
	// 181 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x8e, 0xb1, 0x0a, 0xc2, 0x30,
	0x10, 0x86, 0xa9, 0xd6, 0xaa, 0x99, 0x24, 0x83, 0x04, 0x27, 0xe9, 0x20, 0x4e, 0xed, 0xe0, 0x23,
	0x28, 0x62, 0x07, 0x97, 0x2e, 0xce, 0xb1, 0x39, 0xda, 0x42, 0x4c, 0xe4, 0x2e, 0x15, 0xfa, 0x0e,
	0x3e, 0xb4, 0x78, 0x55, 0x07, 0xb7, 0xfb, 0xbe, 0xff, 0xff, 0xe1, 0xc4, 0x06, 0x81, 0x7c, 0x87,
	0x15, 0x50, 0x7e, 0x47, 0x1f, 0x7c, 0x5e, 0x42, 0xdd, 0x7a, 0x77, 0xd1, 0xb4, 0x47, 0xd0, 0x01,
	0x4c, 0xc6, 0x5a, 0xa6, 0x27, 0xb0, 0xd6, 0x1f, 0x11, 0xa8, 0xc9, 0xce, 0x40, 0xa4, 0x6b, 0xc8,
	0x0e, 0x60, 0xdb, 0x07, 0x60, 0x3f, 0x4c, 0x28, 0x7d, 0x46, 0x62, 0xf1, 0x3f, 0x97, 0x2b, 0x31,
	0x43, 0x76, 0x85, 0x51, 0xd1, 0x3a, 0xda, 0xce, 0xcb, 0x1f, 0x4b, 0x25, 0xa6, 0x95, 0xef, 0x5c,
	0xc0, 0x5e, 0x8d, 0x38, 0xfa, 0xa2, 0x5c, 0x8a, 0xa4, 0xd1, 0xce, 0x58, 0x50, 0x63, 0x0e, 0x3e,
	0x24, 0xa5, 0x88, 0x9d, 0xbe, 0x81, 0x8a, 0xd9, 0xf2, 0xfd, 0xee, 0xda, 0x96, 0x42, 0x61, 0xd4,
	0x64, 0xe8, 0x0e, 0x74, 0x4d, 0xf8, 0xf3, 0xdd, 0x2b, 0x00, 0x00, 0xff, 0xff, 0x70, 0x5c, 0x00,
	0x15, 0xe3, 0x00, 0x00, 0x00,
}
